### ISSUE TITLE
Add and render version tags

### ISSUE THREAD

**Issue by johnjohndoe** [petrnohejl/android-cheatsheet-for-graphic-designers#3]
To enable everybody to see which version of the document is online on GitHub pages I suggest you introduce version tags. These should be rendered into the website. Optionally, you could make the version tag a clickable link referring to the repository tag.

**Comment by petrnohejl** [comment]
Interesting idea, but it could be little bit bothering to create new version with every little change in the document. What about to add last update info (date) via JavaScript, and don't to use tags? What do you think?

**Comment by johnjohndoe** [comment]
How would you realize this? Parsing the time stamp of the HEAD commit?

**Comment by petrnohejl** [comment]
I added last modified info to the footer of the page. It is automatically rendered via JavaScript.

**Comment by johnjohndoe** [comment]
Looks good. Thank you.
